# render.yaml (最终免费版 - 使用 honcho)

services:
  # 1. Web Service (现在它也负责运行 Worker)
  - type: web
    name: douyin-reporter
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    # 【核心修改】启动命令现在使用 honcho
    startCommand: "honcho start" 
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: douyin-reporter-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: douyin-reporter-redis
          property: connectionString
      # --- 私密环境变量在这里声明 ---
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SILICONFLOW_API_KEY
        sync: false

  # 2. Redis Service
  - type: redis
    name: douyin-reporter-redis
    plan: free

# 定义数据库服务
databases:
  - name: douyin-reporter-db
    plan: free