"""Create initial tables for user and livedata

Revision ID: 25eabb51909b
Revises: 
Create Date: 2025-07-01 16:32:48.188832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25eabb51909b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('live_date', sa.Date(), nullable=False),
    sa.Column('live_start_time', sa.String(length=50), nullable=False),
    sa.Column('gmv', sa.Float(), nullable=True),
    sa.Column('gpm', sa.Float(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('buyer_count', sa.Integer(), nullable=True),
    sa.Column('click_to_order_ratio', sa.Float(), nullable=True),
    sa.Column('view_to_order_ratio', sa.Float(), nullable=True),
    sa.Column('expose_to_view_ratio', sa.Float(), nullable=True),
    sa.Column('view_to_interact_ratio', sa.Float(), nullable=True),
    sa.Column('avg_watch_time_seconds', sa.Integer(), nullable=True),
    sa.Column('new_followers', sa.Integer(), nullable=True),
    sa.Column('follower_order_ratio', sa.Float(), nullable=True),
    sa.Column('avg_online_users', sa.Integer(), nullable=True),
    sa.Column('vv', sa.Integer(), nullable=True),
    sa.Column('chart_paths', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_date', 'live_start_time', name='_live_date_start_time_uc')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('live_data')
    # ### end Alembic commands ###
